numbers=(10,20,30,40,50)
numbers=list(numbers)
print(numbers)
numbers.append(60)
print(numbers)
numbers=tuple(numbers)
print(numbers)

numbers=list(numbers)
print(numbers)
numbers[2]=35
print(numbers)
numbers=tuple(numbers)
print(numbers)

fruits=('apples','banana','cherry','banana','mango','banana')
fruits=list(fruits)
print(fruits)
print(fruits.count('banana'))
fruits=tuple(fruits)
print(fruits)

fruits=list(fruits)
print(fruits)
fruits.remove('banana')
print(fruits)
fruits=tuple(fruits)
print(fruits)
